integrations:
  asana:
    auth_type: "oauth2_with_refresh"
    url: "https://app.asana.com/-/oauth_authorize"
    backend_url: "https://app.asana.com/-/oauth_token"
    grant_type: "authorization_code"
    client_id: ${ASANA_CLIENT_ID}
    client_secret: ${ASANA_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"

  confluence:
    auth_type: "oauth2_with_refresh_rotating"
    url: "https://auth.atlassian.com/authorize"
    backend_url: "https://auth.atlassian.com/oauth/token"
    grant_type: "authorization_code"
    client_id: ${CONFLUENCE_CLIENT_ID}
    client_secret: ${CONFLUENCE_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "read offline_access read:confluence-space.summary read:confluence-props manage:confluence-configuration read:confluence-content.all read:confluence-content.summary search:confluence read:confluence-content.permission read:confluence-user read:confluence-groups readonly:content.attachment:confluence read:content:confluence read:content-details:confluence read:space-details:confluence read:page:confluence read:blogpost:confluence read:custom-content:confluence read:comment:confluence read:template:confluence read:label:confluence read:relation:confluence read:space:confluence read:space.property:confluence read:content.metadata:confluence read:task:confluence read:whiteboard:confluence read:database:confluence read:folder:confluence"
    additional_frontend_params:
      audience: "api.atlassian.com"
      prompt: "consent"
      response_mode: "query"
      state: "YOUR_USER_BOUND_VALUE"

  dropbox:
    auth_type: "oauth2_with_refresh"
    url: "https://www.dropbox.com/oauth2/authorize"
    backend_url: "https://api.dropboxapi.com/oauth2/token"
    grant_type: "authorization_code"
    client_id: ${DROPBOX_CLIENT_ID}
    client_secret: ${DROPBOX_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    additional_frontend_params:
      token_access_type: "offline"

  gmail:
    auth_type: "oauth2_with_refresh"
    url: "https://accounts.google.com/o/oauth2/auth"
    backend_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    client_id: ${GMAIL_CLIENT_ID}
    client_secret: ${GMAIL_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "https://www.googleapis.com/auth/gmail.readonly"
    additional_frontend_params:
      access_type: "offline"
      prompt: "consent"

  google_calendar:
    auth_type: "oauth2_with_refresh"
    url: "https://accounts.google.com/o/oauth2/auth"
    backend_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    client_id: ${GOOGLE_CALENDAR_CLIENT_ID}
    client_secret: ${GOOGLE_CALENDAR_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "https://www.googleapis.com/auth/calendar.events.public.readonly https://www.googleapis.com/auth/calendar.freebusy https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.calendars.readonly https://www.googleapis.com/auth/calendar.events.owned.readonly https://www.googleapis.com/auth/calendar.events.readonly"
    additional_frontend_params:
      access_type: "offline"
      prompt: "consent"

  google_drive:
    auth_type: "oauth2_with_refresh"
    url: "https://accounts.google.com/o/oauth2/auth"
    backend_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    client_id: ${GOOGLE_DRIVE_CLIENT_ID}
    client_secret: ${GOOGLE_DRIVE_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "https://www.googleapis.com/auth/docs https://www.googleapis.com/auth/drive.photos.readonly https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.metadata https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/gmail.readonly"
    additional_frontend_params:
      access_type: "offline"
      prompt: "consent"

  hubspot:
    auth_type: "oauth2_with_refresh"
    url: "https://app.hubspot.com/oauth/authorize"
    backend_url: "https://api.hubapi.com/oauth/v1/token"
    grant_type: "authorization_code"
    client_id: ${HUBSPOT_CLIENT_ID}
    client_secret: ${HUBSPOT_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "crm.objects.companies.read crm.objects.contacts.read crm.objects.deals.read oauth tickets"

  intercom:
    auth_type: "oauth2"
    url: "https://app.intercom.com/oauth"
    backend_url: "https://api.intercom.io/auth/eagle/token"
    grant_type: "authorization_code"
    client_id: ${INTERCOM_CLIENT_ID}
    client_secret: ${INTERCOM_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "read write"

  jira:
    auth_type: "oauth2_with_refresh_rotating"
    url: "https://auth.atlassian.com/authorize"
    backend_url: "https://auth.atlassian.com/oauth/token"
    grant_type: "authorization_code"
    client_id: ${JIRA_CLIENT_ID}
    client_secret: ${JIRA_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "read offline_access manage:jira-configuration manage:jira-project read:jira-user read:jira-work read:workflow:jira read:application-role:jira read:avatar:jira read:group:jira read:issue-type:jira read:issue-type-hierarchy:jira read:user:jira read:project:jira read:project-category:jira read:project.component:jira read:project.property:jira read:project-version:jira read:workflow:jira"
    additional_frontend_params:
      audience: "api.atlassian.com"
      prompt: "consent"
      response_mode: "query"
      state: "YOUR_USER_BOUND_VALUE"

  monday:
    auth_type: "oauth2"
    url: "https://auth.monday.com/oauth2/authorize"
    backend_url: "https://auth.monday.com/oauth2/token"
    grant_type: "authorization_code"
    client_id: ${MONDAY_CLIENT_ID}
    client_secret: ${MONDAY_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "me:read boards:read docs:read workspaces:read users:read account:read updates:read assets:read tags:read teams:read"

  notion:
    auth_type: "oauth2"
    url: "https://api.notion.com/v1/oauth/authorize"
    backend_url: "https://api.notion.com/v1/oauth/token"
    grant_type: "authorization_code"
    client_id: ${NOTION_CLIENT_ID}
    client_secret: ${NOTION_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "header"
    additional_frontend_params:
      owner: "user"

  outlook_mail:
    auth_type: "oauth2_with_refresh_rotating"
    url: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
    backend_url: "https://login.microsoftonline.com/common/oauth2/v2.0/token"
    grant_type: "authorization_code"
    client_id: ${OUTLOOK_MAIL_CLIENT_ID}
    client_secret: ${OUTLOOK_MAIL_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "offline_access https://graph.microsoft.com/User.Read https://graph.microsoft.com/MailboxFolder.Read https://graph.microsoft.com/Mail.Read"
    additional_frontend_params:
      response_mode: "query"

  slack:
    auth_type: "oauth2"
    url: "https://slack.com/oauth/v2/authorize"
    backend_url: "https://slack.com/api/oauth.v2.access"
    grant_type: "authorization_code"
    client_id: ${SLACK_CLIENT_ID}
    client_secret: ${SLACK_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "app_mentions:read,channels:history,channels:join,channels:read,groups:history,groups:read,im:history,im:read,mpim:history,mpim:read,users:read"

  stripe:
    auth_type: "api_key"

  todoist:
    auth_type: "oauth2"
    url: "https://todoist.com/oauth/authorize"
    backend_url: "https://todoist.com/oauth/access_token"
    grant_type: "authorization_code"
    client_id: ${TODOIST_CLIENT_ID}
    client_secret: ${TODOIST_CLIENT_SECRET}
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "data:read"

  trello:
    auth_type: "trello_auth"
    url: "https://trello.com/1/authorize"
    key: ${TRELLO_CLIENT_ID}
    scope: "read"
    callback_method: "fragment"
    expiration: "never"
    name: "Airweave Integration"